### ISSUE TITLE
[feature] cli redeploy

### ISSUE THREAD

**Issue by alexx855** [zeabur/cli#97]
### Is your feature request related to a problem? Please describe.

Yes, i need to redeploy my prebuild project so the image container its updated

### Describe the solution you'd like

Add redeploy command to CLI to redeploy prebuild services

### Describe alternatives you've considered

I haven't found any alternative, if there is any, please let me know.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pan93412** [comment]
**Prebuilt** does not have the *redeploy* concept since we do not need to build your Docker image to start it. To apply your service changes, you only need to `restart`:

```bash
zeabur service restart
```

For Git services, we also provide the `redeploy` command:

```bash
zeabur service redeploy
```

By the way, you can join our Discord group (<https://zeabur.com/dc>), where we can respond your questions much faster!
